# Generated by Django 4.1.7 on 2023-03-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_address',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
