# Generated by Django 4.1.5 on 2023-04-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0002_user_address_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_address',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_address',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
