# Generated by Django 4.1.5 on 2023-04-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0003_user_address_name_user_address_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
