# Generated by Django 4.1.5 on 2023-04-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0004_alter_user_address_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
