# Generated by Django 4.1.7 on 2023-03-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_name', models.CharField(max_length=255)),
                ('ad_image', models.ImageField(upload_to='adimage')),
                ('ad_description', models.CharField(max_length=255)),
            ],
        ),
    ]
