# Generated by Django 4.1.7 on 2023-03-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_name', models.CharField(max_length=255)),
                ('ad_image', models.ImageField(upload_to='ad_image')),
                ('ad_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='ads',
        ),
    ]
