# Generated by Django 4.1.5 on 2023-04-02 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('advertisement', '0002_advertisement_delete_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='ad_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.brand'),
        ),
    ]
