# Generated by Django 4.1.7 on 2023-03-23 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('cart_total', models.PositiveIntegerField()),
                ('tax', models.PositiveIntegerField()),
                ('grand_total', models.PositiveIntegerField()),
                ('payment_method', models.CharField(default='RazorPay', max_length=30)),
                ('is_paid', models.BooleanField(default=True)),
                ('paid_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
